# Properties file for integration tests
# Overrides application.yml default properties
spring:
  datasource:
    host: localhost:3306
    db: warehouse
    username: ${LOCAL_DB_USER}
    password: ${LOCAL_DB_PASS}
    initialization-mode: always

  jpa:
    show-sql: true
    hibernate:
      sql: debug
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL8Dialect