# Properties file for local/dev enviroment
# You need to configure the environment variable in your IDE, more info in README.md
# Overrides application.yml default properties
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/warehouse?useSSL=false&serverTimezone=UTC
    username: root
    password: asd123456
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect