# Properties file for local/dev enviroment
# You need to configure the environment variable in your IDE, more info in README.md
# Overrides application.yml default properties
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/warehouse?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&jdbcCompliantTruncation=false
    username: ${LOCAL_DB_USER}
    password: ${LOCAL_DB_PASS}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL8Dialect