spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
  datasource:
    #initialization-mode: always
    #data: classpath:/data.sql
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://proxysql.master.meliseginf.com:6612/[NombreDBMELI]?useSSL=true&serverTimezone=UTC&characterEncoding=UTF-8
    #    username: ${LOCAL_DB_USER}
    #    password: ${LOCAL_DB_PASS}
    url: jdbc:mysql://localhost:3306/groupOne?useSSL=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: ${LOCAL_DB_USER}
    password: ${LOCAL_DB_PASSWORD}