# "prod" suffix properties file. Scopes name samples: "prod", "web-prod", "api-prod", etc.
# Overrides application.yml default properties
spring:
  datasource:
    host: DB_MYSQL_DESAENV04_WHSERGIO_WHSERGIO_ENDPOINT
    db: whsergio
    username: whsergio_WPROD
    password: DB_MYSQL_DESAENV04_WHSERGIO_WHSERGIO_WPROD
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      sql: debug
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL8Dialect
