# "prod" suffix properties file. Scopes name samples: "prod", "web-prod", "api-prod", etc.
# Overrides application.yml default properties
spring:
  datasource:
    host: proxysql.master.meliseginf.com:6612
    db: whousefede
    username: ${FURY_DB_USER}
    password: ${FURY_DB_PASS}
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      sql: debug
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL8Dialect